/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import Entidades.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Win10
 */
public class home extends javax.swing.JFrame {
//inicializamos l
    ArrayList<cliente> lClie;
    DefaultTableModel modeloCli;
    DefaultTableModel modeloLlamada;
    DateFormat formatoFecha;
    double CostoLlamada;
    
    public home() {
        initComponents();
        lClie = new ArrayList<cliente>();
        modeloCli = (DefaultTableModel) this.jtClientetable.getModel();
        modeloLlamada= (DefaultTableModel) this.jtllamada_table.getModel();
        formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientetable = new javax.swing.JTable();
        clientesTxt = new javax.swing.JTextField();
        llamadasTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtllamada_table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clientes");

        jLabel2.setText("Llamadas");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtClientetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Dui", "Departamento"
            }
        ));
        jtClientetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtClientetable);

        clientesTxt.setName("clientetxt"); // NOI18N
        clientesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesTxtActionPerformed(evt);
            }
        });

        llamadasTxt.setName("llamadatxt"); // NOI18N

        jtllamada_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Hora", "Duracin", "NumeroOrigen", "NumeroDestino", "Recargo por Llamada"
            }
        ));
        jScrollPane2.setViewportView(jtllamada_table);

        jLabel5.setText("0");

        jLabel4.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(llamadasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jButton1)
                        .addComponent(clientesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(llamadasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int maxClie = Integer.parseInt(this.clientesTxt.getText());
    int maxLlamada = Integer.parseInt(this.llamadasTxt.getText());
    Date inicio = new Date();
    
    // Limpiamos las tablas antes de agregar nuevos datos
    modeloCli.setRowCount(0);
    modeloLlamada.setRowCount(0);
    
    // Creamos clientes y llamadas
    for (int i = 0; i < maxClie; i++) {
        cliente nuevoCliente = new cliente("C" + i, "123456789-0", "Dept" + i);
        nuevoCliente.Illamada = new ArrayList<>();
        
        for (int j = 0; j < maxLlamada; j++) {
            Date fechaHora = new Date();
            int duracion = (int) (Math.random() * 60); // Duración aleatoria en minutos
            String numeroOrigen = "010" + (int)(Math.random() * 1000);
            String numeroDestino = "020" + (int)(Math.random() * 1000);
            double costoLlamada = Math.round(Math.random() * 10); // Costo aleatorio
            
            llamada nuevaLlamada = new llamada(fechaHora, duracion, numeroOrigen, numeroDestino, costoLlamada);
            nuevoCliente.Illamada.add(nuevaLlamada);
            
            // Agregamos la llamada a la tabla
            String[] registroL = {
                formatoFecha.format(nuevaLlamada.FechaHora),
                Integer.toString(nuevaLlamada.Duracion),
                nuevaLlamada.NumeroOrigen,
                nuevaLlamada.NumeroDestino,
                Double.toString(nuevaLlamada.CostoLlamada)
            };
            modeloLlamada.addRow(registroL);
        }
        
        // Agregamos el cliente a la tabla
        String[] registroC = {nuevoCliente.Codigo, nuevoCliente.Dui, nuevoCliente.Departamento};
        modeloCli.addRow(registroC);
        
        // Agregamos el cliente a la lista
        lClie.add(nuevoCliente);
    }
    
    Date fin = new Date();
    long duracion = fin.getTime() - inicio.getTime();
    this.jLabel4.setText(Long.toString(duracion) + " ms");
    this.jLabel5.setText(Long.toString(duracion / 1000) + " s");
     this.jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clientesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesTxtActionPerformed

    private void jtClientetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientetableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtClientetableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientesTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtClientetable;
    private javax.swing.JTable jtllamada_table;
    private javax.swing.JTextField llamadasTxt;
    // End of variables declaration//GEN-END:variables
}
